(function(){var h={},mt={},c={id:"c0f0742eeb83d6ab6614a81723b00197",dm:["xuebuyuan.com"],js:"tongji.baidu.com/hm-web/js/",etrk:[],icon:'/hmt/icon/21|gif|20|20',ctrk:true,align:1,nv:-1,vdur:1800000,age:31536000000,rec:1,rp:[[14387, 2]],trust:0,vcard:0,qiao:0,lxb:0,conv:0,med:0,cvcc:'',cvcf:[],apps:''};var r=void 0,s=!0,t=null,u=!1;mt.cookie={};mt.cookie.set=function(a,d,b){var g;b.N&&(g=new Date,g.setTime(g.getTime()+b.N));document.cookie=a+"="+d+(b.domain?"; domain="+b.domain:"")+(b.path?"; path="+b.path:"")+(g?"; expires="+g.toGMTString():"")+(b.xb?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:t};mt.g={};mt.g.Z=function(a){return document.getElementById(a)};
mt.g.P=function(a,d){var b=[],g=[];if(!a)return g;for(;a.parentNode!=t;){for(var f=0,n=0,l=a.parentNode.childNodes.length,p=0;p<l;p++){var e=a.parentNode.childNodes[p];if(e.nodeName===a.nodeName&&(f++,e===a&&(n=f),0<n&&1<f))break}if((l=""!==a.id)&&d){b.unshift("#"+encodeURIComponent(a.id));break}else l&&(l="#"+encodeURIComponent(a.id),l=0<b.length?l+">"+b.join(">"):l,g.push(l)),b.unshift(encodeURIComponent(String(a.nodeName).toLowerCase())+(1<f?"["+n+"]":""));a=a.parentNode}g.push(b.join(">"));return g};
mt.g.Ka=function(a){return(a=mt.g.P(a,s))&&a.length?String(a[0]):""};mt.g.rb=function(a){return mt.g.P(a,u)};mt.g.Ca=function(a){var d;for(d="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==d)return a;return t};mt.g.Ea=function(a){return 9===a.nodeType?a:a.ownerDocument||a.document};
mt.g.Ia=function(a){var d={top:0,left:0};if(!a)return d;var b=mt.g.Ea(a).documentElement;"undefined"!==typeof a.getBoundingClientRect&&(d=a.getBoundingClientRect());return{top:d.top+(window.pageYOffset||b.scrollTop)-(b.clientTop||0),left:d.left+(window.pageXOffset||b.scrollLeft)-(b.clientLeft||0)}};
(mt.g.fa=function(){function a(){if(!a.G){a.G=s;for(var d=0,b=g.length;d<b;d++)g[d]()}}function d(){try{document.documentElement.doScroll("left")}catch(g){setTimeout(d,1);return}a()}var b=u,g=[],f;document.addEventListener?f=function(){document.removeEventListener("DOMContentLoaded",f,u);a()}:document.attachEvent&&(f=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",f),a())});(function(){if(!b)if(b=s,"complete"===document.readyState)a.G=s;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",
f,u),window.addEventListener("load",a,u);else if(document.attachEvent){document.attachEvent("onreadystatechange",f);window.attachEvent("onload",a);var g=u;try{g=window.frameElement==t}catch(l){}document.documentElement.doScroll&&g&&d()}})();return function(d){a.G?d():g.push(d)}}()).G=u;mt.event={};mt.event.c=function(a,d,b){a.attachEvent?a.attachEvent("on"+d,function(d){b.call(a,d)}):a.addEventListener&&a.addEventListener(d,b,u)};
mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=u};
(function(){var a=mt.event;mt.f={};mt.f.ca=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.f.Va=/msie (\d+\.\d+)/i.test(navigator.userAgent)?document.documentMode||+RegExp.$1:r;mt.f.cookieEnabled=navigator.cookieEnabled;mt.f.javaEnabled=navigator.javaEnabled();mt.f.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.f.bb=(window.screen.width||0)+"x"+(window.screen.height||0);mt.f.colorDepth=window.screen.colorDepth||0;mt.f.C=function(){var a;
a=a||document;return parseInt(window.pageYOffset||a.documentElement.scrollTop||a.body&&a.body.scrollTop||0,10)};mt.f.D=function(){var a=document;return parseInt(window.innerHeight||a.documentElement.clientHeight||a.body&&a.body.clientHeight||0,10)};mt.f.orientation=0;(function(){function d(){var a=0;window.orientation!==r&&(a=window.orientation);screen&&(screen.orientation&&screen.orientation.angle!==r)&&(a=screen.orientation.angle);mt.f.orientation=a}d();a.c(window,"orientationchange",d)})();return mt.f})();
mt.l={};mt.l.parse=function(){return(new Function('return (" + source + ")'))()};
mt.l.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var d=b[a];if(d)return d;d=a.charCodeAt();return"\\u00"+Math.floor(d/16).toString(16)+(d%16).toString(16)}));return'"'+a+'"'}function d(a){return 10>a?"0"+a:a}var b={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(b){switch(typeof b){case "undefined":return"undefined";case "number":return isFinite(b)?String(b):"null";case "string":return a(b);case "boolean":return String(b);
default:if(b===t)return"null";if(b instanceof Array){var f=["["],n=b.length,l,p,e;for(p=0;p<n;p++)switch(e=b[p],typeof e){case "undefined":case "function":case "unknown":break;default:l&&f.push(","),f.push(mt.l.stringify(e)),l=1}f.push("]");return f.join("")}if(b instanceof Date)return'"'+b.getFullYear()+"-"+d(b.getMonth()+1)+"-"+d(b.getDate())+"T"+d(b.getHours())+":"+d(b.getMinutes())+":"+d(b.getSeconds())+'"';l=["{"];p=mt.l.stringify;for(n in b)if(Object.prototype.hasOwnProperty.call(b,n))switch(e=
b[n],typeof e){case "undefined":case "unknown":case "function":break;default:f&&l.push(","),f=1,l.push(p(n)+":"+p(e))}l.push("}");return l.join("")}}}();mt.lang={};mt.lang.d=function(a,d){return"[object "+d+"]"==={}.toString.call(a)};mt.lang.ub=function(a){return mt.lang.d(a,"Number")&&isFinite(a)};mt.lang.wb=function(a){return mt.lang.d(a,"String")};mt.lang.h=function(a){return a.replace?a.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):a};mt.localStorage={};
mt.localStorage.L=function(){if(!mt.localStorage.i)try{mt.localStorage.i=document.createElement("input"),mt.localStorage.i.type="hidden",mt.localStorage.i.style.display="none",mt.localStorage.i.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.i)}catch(a){return u}return s};
mt.localStorage.set=function(a,d,b){var g=new Date;g.setTime(g.getTime()+b||31536E6);try{window.localStorage?(d=g.getTime()+"|"+d,window.localStorage.setItem(a,d)):mt.localStorage.L()&&(mt.localStorage.i.expires=g.toUTCString(),mt.localStorage.i.load(document.location.hostname),mt.localStorage.i.setAttribute(a,d),mt.localStorage.i.save(document.location.hostname))}catch(f){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var d=a.indexOf("|"),b=a.substring(0,d)-0;if(b&&b>(new Date).getTime())return a.substring(d+1)}}else if(mt.localStorage.L())try{return mt.localStorage.i.load(document.location.hostname),mt.localStorage.i.getAttribute(a)}catch(g){}return t};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.L())try{mt.localStorage.i.load(document.location.hostname),mt.localStorage.i.removeAttribute(a),mt.localStorage.i.save(document.location.hostname)}catch(d){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,d){if(window.sessionStorage)try{window.sessionStorage.setItem(a,d)}catch(b){}};
mt.sessionStorage.get=function(a){return window.sessionStorage?window.sessionStorage.getItem(a):t};mt.sessionStorage.remove=function(a){window.sessionStorage&&window.sessionStorage.removeItem(a)};mt.ha={};mt.ha.log=function(a,d){var b=new Image,g="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[g]=b;b.onload=b.onerror=b.onabort=function(){b.onload=b.onerror=b.onabort=t;b=window[g]=t;d&&d(a)};b.src=a};mt.K={};
mt.K.Ma=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var d=navigator.plugins["Shockwave Flash"];d&&d.description&&(a=d.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=d.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(b){}return a};
mt.K.va=function(a,d,b,g,f){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+a+'" width="'+b+'" height="'+g+'"><param name="movie" value="'+d+'" /><param name="flashvars" value="'+(f||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+a+'" width="'+b+'" height="'+g+'" src="'+d+'" flashvars="'+(f||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.j=function(a,d){var b=a.match(RegExp("(^|&|\\?|#)("+d+")=([^&#]*)(&|$|#)",""));return b?b[3]:t};mt.url.tb=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:t};mt.url.Ga=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):t};mt.url.aa=function(a){return(a=mt.url.Ga(a))?a.replace(/:\d+$/,""):a};mt.url.P=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):t};
(function(){function a(){for(var a=u,b=document.getElementsByTagName("script"),g=b.length,g=100<g?100:g,f=0;f<g;f++){var n=b[f].src;if(n&&0===n.indexOf("https://hm.baidu.com/h")){a=s;break}}return a}return h.Ba=a})();var A=h.Ba;
h.p={Ua:"http://tongji.baidu.com/hm-web/welcome/ico",T:"hm.baidu.com/hm.gif",oa:"baidu.com",Ra:"hmmd",Sa:"hmpl",nb:"utm_medium",Qa:"hmkw",pb:"utm_term",Oa:"hmci",mb:"utm_content",Ta:"hmsr",ob:"utm_source",Pa:"hmcu",lb:"utm_campaign",z:0,m:Math.round(+new Date/1E3),X:Math.round(+new Date/1E3)%65535,protocol:"https:"===document.location.protocol?"https:":"http:",H:A()||"https:"===document.location.protocol?"https:":"http:",vb:0,ta:6E5,cb:5E3,ua:5,W:1024,sa:1,w:2147483647,ia:"cc cf ci ck cl cm cp cu cw ds vl ep et fl ja ln lo lt rnd si su v cv lv api sn ct u tt".split(" ")};
(function(){var a={s:{},c:function(a,b){this.s[a]=this.s[a]||[];this.s[a].push(b)},B:function(a,b){this.s[a]=this.s[a]||[];for(var g=this.s[a].length,f=0;f<g;f++)this.s[a][f](b)}};return h.r=a})();
(function(){function a(a,g){var f=document.createElement("script");f.charset="utf-8";d.d(g,"Function")&&(f.readyState?f.onreadystatechange=function(){if("loaded"===f.readyState||"complete"===f.readyState)f.onreadystatechange=t,g()}:f.onload=function(){g()});f.src=a;var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(f,n)}var d=mt.lang;return h.load=a})();
(function(){function a(){var a="";h.b.a.nv?(a=encodeURIComponent(document.referrer),window.sessionStorage?b.set("Hm_from_"+c.id,a):d.set("Hm_from_"+c.id,a,864E5)):a=(window.sessionStorage?b.get("Hm_from_"+c.id):d.get("Hm_from_"+c.id))||"";return a}var d=mt.localStorage,b=mt.sessionStorage;return h.Y=a})();
(function(){var a=h.p,d=mt.K,b={init:function(){if(""!==c.icon){var b;b=c.icon.split("|");var f=a.Ua+"?s="+c.id,n=("http:"==a.protocol?"http://eiv":"https://bs")+".baidu.com"+b[0]+"."+b[1];switch(b[1]){case "swf":b=d.va("HolmesIcon"+a.m,n,b[2],b[3],"s="+f);break;case "gif":b='<a href="'+f+'" target="_blank"><img border="0" src="'+n+'" width="'+b[2]+'" height="'+b[3]+'"></a>';break;default:b='<a href="'+f+'" target="_blank">'+b[0]+"</a>"}document.write(b)}}};h.r.c("pv-b",b.init);return b})();
(function(){var a=mt.g,d=mt.lang,b=mt.event,g=mt.f,f=h.p,n=h.r,l=[],p={ka:function(){c.ctrk&&(b.c(document,"mouseup",p.ra()),b.c(window,"unload",function(){p.I()}),setInterval(function(){p.I()},f.ta))},ra:function(){return function(a){a=p.Da(a);if(""!==a){var b=(f.H+"//"+f.T+"?"+h.b.ga().replace(/ep=[^&]*/,"ep="+encodeURIComponent(a))).length;b+(f.w+"").length>f.W||(b+encodeURIComponent(l.join("!")+(l.length?"!":"")).length+(f.w+"").length>f.W&&p.I(),l.push(a),(l.length>=f.ua||/\*a\*/.test(a))&&p.I())}}},
Da:function(k){var b=k.target||k.srcElement;if(0===f.sa){var m=(b.tagName||"").toLowerCase();if("embed"==m||"object"==m)return""}var q;g.ca?(q=Math.max(document.documentElement.scrollTop,document.body.scrollTop),m=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),m=k.clientX+m,q=k.clientY+q):(m=k.pageX,q=k.pageY);k=p.Ha(k,b,m,q);var e=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:m-=e/2;break;case 2:m-=e}e=[];e.push(m);
e.push(q);e.push(k.Xa);e.push(k.Ya);e.push(k.$a);e.push(d.h(k.Za));e.push(k.qb);e.push(k.Na);(b="a"===(b.tagName||"").toLowerCase()?b:a.Ca(b))?(e.push("a"),e.push(d.h(encodeURIComponent(b.href)))):e.push("b");return e.join("*")},Ha:function(k,b,m,q){k=a.Ka(b);var e=0,f=0,y=0,l=0;if(b&&(e=b.offsetWidth||b.clientWidth,f=b.offsetHeight||b.clientHeight,l=a.Ia(b),y=l.left,l=l.top,d.d(b.getBBox,"Function")&&(f=b.getBBox(),e=f.width,f=f.height),"html"===(b.tagName||"").toLowerCase()))e=Math.max(e,b.clientWidth),
f=Math.max(f,b.clientHeight);return{Xa:Math.round(100*((m-y)/e)),Ya:Math.round(100*((q-l)/f)),$a:g.orientation,Za:k,qb:e,Na:f}},I:function(){0!==l.length&&(h.b.a.et=2,h.b.a.ep=l.join("!"),h.b.k(),l=[])}},e={ma:function(){c.ctrk&&setInterval(e.eb,f.cb)},eb:function(){var a=g.C()+g.D();0<a-h.b.a.vl&&(h.b.a.vl=a)}};n.c("pv-b",p.ka);n.c("pv-b",e.ma);return p})();
(function(){var a=mt.g,d=h.p,b=h.load,g=h.Y;h.r.c("pv-b",function(){var f=d.protocol+"//crs.baidu.com/";c.rec&&a.fa(function(){for(var n=0,l=c.rp.length;n<l;n++){var p=c.rp[n][0],e=c.rp[n][1],k=a.Z("hm_t_"+p);if(e&&!(2==e&&!k||k&&""!==k.innerHTML))k="",k=Math.round(Math.random()*d.w),k=4==e?f+"hl.js?"+["siteId="+c.id,"planId="+p,"rnd="+k].join("&"):f+"t.js?"+["siteId="+c.id,"planId="+p,"from="+g(),"referer="+encodeURIComponent(document.referrer),"title="+encodeURIComponent(document.title),"rnd="+
k].join("&"),b(k)}})})})();(function(){var a=h.p,d=h.load,b=h.Y;h.r.c("pv-b",function(){if(c.trust&&c.vcard){var g="https://tag.baidu.com/vcard/v.js?"+["siteid="+c.vcard,"url="+encodeURIComponent(document.location.href),"source="+b(),"rnd="+Math.round(Math.random()*a.w),"hm=1"].join("&");d(g)}})})();
(function(){function a(){return function(){h.b.a.nv=0;h.b.a.st=4;h.b.a.et=3;h.b.a.ep=h.M.Ja()+","+h.M.Fa();h.b.k()}}function d(){clearTimeout(z);var a;w&&(a="visible"==document[w]);y&&(a=!document[y]);p="undefined"==typeof a?s:a;if((!l||!e)&&p&&k)x=s,m=+new Date;else if(l&&e&&(!p||!k))x=u,q+=+new Date-m;l=p;e=k;z=setTimeout(d,100)}function b(a){var k=document,b="";if(a in k)b=a;else for(var m=["webkit","ms","moz","o"],d=0;d<m.length;d++){var q=m[d]+a.charAt(0).toUpperCase()+a.slice(1);if(q in k){b=
q;break}}return b}function g(a){if(!("focus"==a.type||"blur"==a.type)||!(a.target&&a.target!=window))k="focus"==a.type||"focusin"==a.type?s:u,d()}var f=mt.event,n=h.r,l=s,p=s,e=s,k=s,v=+new Date,m=v,q=0,x=s,w=b("visibilityState"),y=b("hidden"),z;d();(function(){var a=w.replace(/[vV]isibilityState/,"visibilitychange");f.c(document,a,d);f.c(window,"pageshow",d);f.c(window,"pagehide",d);"object"==typeof document.onfocusin?(f.c(document,"focusin",g),f.c(document,"focusout",g)):(f.c(window,"focus",g),
f.c(window,"blur",g))})();h.M={Ja:function(){return+new Date-v},Fa:function(){return x?+new Date-m+q:q}};n.c("pv-b",function(){f.c(window,"unload",a())});return h.M})();
(function(){var a=mt.lang,d=h.p,b=h.load,g={Wa:function(f){if((window._dxt===r||a.d(window._dxt,"Array"))&&"undefined"!==typeof h.b){var g=h.b.O();b([d.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(g)].join(""),f)}},jb:function(b){if(a.d(b,"String")||a.d(b,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",b])}};return h.wa=g})();
(function(){function a(a,b,m,d){if(!(a===r||b===r||d===r)){if(""===a)return[b,m,d].join("*");a=String(a).split("!");for(var e,f=u,g=0;g<a.length;g++)if(e=a[g].split("*"),String(b)===e[0]){e[1]=m;e[2]=d;a[g]=e.join("*");f=s;break}f||a.push([b,m,d].join("*"));return a.join("!")}}function d(a){for(var e in a)if({}.hasOwnProperty.call(a,e)){var m=a[e];b.d(m,"Object")||b.d(m,"Array")?d(m):a[e]=String(m)}}var b=mt.lang,g=mt.l,f=mt.f,n=h.p,l=h.r,p=h.wa,e={A:[],J:0,da:u,o:{V:"",page:""},init:function(){e.e=
0;l.c("pv-b",function(){e.xa();e.za()});l.c("pv-d",function(){e.Aa();e.o.page=""});l.c("stag-b",function(){h.b.a.api=e.e||e.J?e.e+"_"+e.J:"";h.b.a.ct=[decodeURIComponent(h.b.getData("Hm_ct_"+c.id)||""),e.o.V,e.o.page].join("!")});l.c("stag-d",function(){h.b.a.api=0;e.e=0;e.J=0})},xa:function(){var a=window._hmt||[];if(!a||b.d(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,k=0;k<arguments.length;k++){var d=arguments[k];b.d(d,"Array")&&(a.cmd[a.id].push(d),"_setAccount"===
d[0]&&(1<d.length&&/^[0-9a-f]{32}$/.test(d[1]))&&(d=d[1],a.id=d,a.cmd[d]=a.cmd[d]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},za:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],m=/^_track(Event|MobConv|Order|RTEvent)$/,d=0,f=b.length;d<f;d++){var g=b[d];m.test(g[0])?e.A.push(g):e.S(g)}a.cmd[c.id]={push:e.S}},Aa:function(){if(0<e.A.length)for(var a=0,b=e.A.length;a<b;a++)e.S(e.A[a]);e.A=t},S:function(a){var d=a[0];if(e.hasOwnProperty(d)&&b.d(e[d],
"Function"))e[d](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{32}$/.test(a[1])&&(e.e|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],u===a||s===a))e.e|=2,h.b.ba=a},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"===a[1].charAt(0)){e.e|=4;h.b.a.et=0;h.b.a.ep="";h.b.a.vl=f.C()+f.D();h.b.Q?(h.b.a.nv=0,h.b.a.st=4):h.b.Q=s;var b=h.b.a.u,d=h.b.a.su;h.b.a.u=n.protocol+"//"+document.location.host+a[1];e.da||(h.b.a.su=document.location.href);h.b.k();h.b.a.u=b;h.b.a.su=d}},_trackEvent:function(a){2<
a.length&&(e.e|=8,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=4,h.b.a.ep=b.h(a[1])+"*"+b.h(a[2])+(a[3]?"*"+b.h(a[3]):"")+(a[4]?"*"+b.h(a[4]):""),h.b.k())},_setCustomVar:function(a){if(!(4>a.length)){var d=a[1],m=a[4]||3;if(0<d&&6>d&&0<m&&4>m){e.J++;for(var f=(h.b.a.cv||"*").split("!"),g=f.length;g<d-1;g++)f.push("*");f[d-1]=m+"*"+b.h(a[2])+"*"+b.h(a[3]);h.b.a.cv=f.join("!");a=h.b.a.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?h.b.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):h.b.ab("Hm_cv_"+
c.id)}}},_setUserTag:function(d){if(!(3>d.length)){var e=b.h(d[1]);d=b.h(d[2]);if(e!==r&&d!==r){var m=decodeURIComponent(h.b.getData("Hm_ct_"+c.id)||""),m=a(m,e,1,d);h.b.setData("Hm_ct_"+c.id,encodeURIComponent(m),c.age)}}},_setVisitTag:function(d){if(!(3>d.length)){var f=b.h(d[1]);d=b.h(d[2]);if(f!==r&&d!==r){var m=e.o.V,m=a(m,f,2,d);e.o.V=m}}},_setPageTag:function(d){if(!(3>d.length)){var f=b.h(d[1]);d=b.h(d[2]);if(f!==r&&d!==r){var m=e.o.page,m=a(m,f,3,d);e.o.page=m}}},_setReferrerOverride:function(a){1<
a.length&&(h.b.a.su=a[1].charAt&&"/"===a[1].charAt(0)?n.protocol+"//"+window.location.host+a[1]:a[1],e.da=s)},_trackOrder:function(a){a=a[1];b.d(a,"Object")&&(d(a),e.e|=16,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=94,h.b.a.ep=g.stringify(a),h.b.k())},_trackMobConv:function(a){if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])e.e|=32,h.b.a.et=93,h.b.a.ep=a,h.b.k()},_trackRTPageview:function(a){a=a[1];b.d(a,"Object")&&(d(a),a=g.stringify(a),512>=encodeURIComponent(a).length&&(e.e|=64,h.b.a.rt=a))},_trackRTEvent:function(a){a=
a[1];if(b.d(a,"Object")){d(a);a=encodeURIComponent(g.stringify(a));var f=function(a){var b=h.b.a.rt;e.e|=128;h.b.a.et=90;h.b.a.rt=a;h.b.k();h.b.a.rt=b},m=a.length;if(900>=m)f.call(this,a);else for(var m=Math.ceil(m/900),q="block|"+Math.round(Math.random()*n.w).toString(16)+"|"+m+"|",l=[],w=0;w<m;w++)l.push(w),l.push(a.substring(900*w,900*w+900)),f.call(this,q+l.join("|")),l=[]}},_setUserId:function(a){a=a[1];p.Wa();p.jb(a)}};e.init();h.pa=e;return h.pa})();
(function(){function a(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=s,this.a={},this.ba=s,this.Q=u,this.init())}var d=mt.url,b=mt.ha,g=mt.K,f=mt.lang,n=mt.cookie,l=mt.f,p=mt.localStorage,e=mt.sessionStorage,k=h.p,v=h.r;a.prototype={R:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length},ea:function(a,b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},F:function(a){for(var b=0;b<c.dm.length;b++)if(-1<
c.dm[b].indexOf("/")){if(this.ea(a,c.dm[b]))return s}else{var e=d.aa(a);if(e&&this.R(e,c.dm[b]))return s}return u},O:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.R(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[\/\?#].*/,"");return a},$:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.ea(document.location.href,d))return d.replace(/^[^\/]+(\/.*)/,"$1")+"/"}return"/"},La:function(){if(!document.referrer)return k.m-k.z>c.vdur?1:4;
var a=u;this.F(document.referrer)&&this.F(document.location.href)?a=s:(a=d.aa(document.referrer),a=this.R(a||"",document.location.hostname));return a?k.m-k.z>c.vdur?1:4:3},getData:function(a){try{return n.get(a)||e.get(a)||p.get(a)}catch(b){}},setData:function(a,b,d){try{n.set(a,b,{domain:this.O(),path:this.$(),N:d}),d?p.set(a,b,d):e.set(a,b)}catch(f){}},ab:function(a){try{n.set(a,"",{domain:this.O(),path:this.$(),N:-1}),e.remove(a),p.remove(a)}catch(b){}},hb:function(){var a,b,d,e,f;k.z=this.getData("Hm_lpvt_"+
c.id)||0;13===k.z.length&&(k.z=Math.round(k.z/1E3));b=this.La();a=4!==b?1:0;if(d=this.getData("Hm_lvt_"+c.id)){e=d.split(",");for(f=e.length-1;0<=f;f--)13===e[f].length&&(e[f]=""+Math.round(e[f]/1E3));for(;2592E3<k.m-e[0];)e.shift();f=4>e.length?2:3;for(1===a&&e.push(k.m);4<e.length;)e.shift();d=e.join(",");e=e[e.length-1]}else d=k.m,e="",f=1;this.setData("Hm_lvt_"+c.id,d,c.age);this.setData("Hm_lpvt_"+c.id,k.m);d=k.m===this.getData("Hm_lpvt_"+c.id)?"1":"0";if(0===c.nv&&this.F(document.location.href)&&
(""===document.referrer||this.F(document.referrer)))a=0,b=4;this.a.nv=a;this.a.st=b;this.a.cc=d;this.a.lt=e;this.a.lv=f},ga:function(){for(var a=[],b=this.a.et,d=0,e=k.ia.length;d<e;d++){var f=k.ia[d],g=this.a[f];"undefined"!==typeof g&&""!==g&&("tt"!==f||"tt"===f&&0===b)&&("ct"!==f||"ct"===f&&0===b)&&a.push(f+"="+encodeURIComponent(g))}switch(b){case 0:a.push("sn="+k.X);this.a.rt&&a.push("rt="+encodeURIComponent(this.a.rt));break;case 3:a.push("sn="+k.X);break;case 90:this.a.rt&&a.push("rt="+this.a.rt)}return a.join("&")},
ib:function(){this.hb();this.a.si=c.id;this.a.su=document.referrer;this.a.ds=l.bb;this.a.cl=l.colorDepth+"-bit";this.a.ln=String(l.language).toLowerCase();this.a.ja=l.javaEnabled?1:0;this.a.ck=l.cookieEnabled?1:0;this.a.lo="number"===typeof _bdhm_top?1:0;this.a.fl=g.Ma();this.a.v="1.2.27";this.a.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");this.a.tt=document.title||"";this.a.vl=l.C()+l.D();var a=document.location.href;this.a.cm=d.j(a,k.Ra)||"";this.a.cp=d.j(a,k.Sa)||d.j(a,k.nb)||"";this.a.cw=
d.j(a,k.Qa)||d.j(a,k.pb)||"";this.a.ci=d.j(a,k.Oa)||d.j(a,k.mb)||"";this.a.cf=d.j(a,k.Ta)||d.j(a,k.ob)||"";this.a.cu=d.j(a,k.Pa)||d.j(a,k.lb)||""},init:function(){try{this.ib(),0===this.a.nv?this.gb():this.U(".*"),h.b=this,this.qa(),v.B("pv-b"),this.fb()}catch(a){var d=[];d.push("si="+c.id);d.push("n="+encodeURIComponent(a.name));d.push("m="+encodeURIComponent(a.message));d.push("r="+encodeURIComponent(document.referrer));b.log(k.H+"//"+k.T+"?"+d.join("&"))}},fb:function(){function a(){v.B("pv-d")}
this.ba?(this.Q=s,this.a.et=0,this.a.ep="",this.a.vl=l.C()+l.D(),this.k(a)):a()},k:function(a){var d=this;d.a.rnd=Math.round(Math.random()*k.w);v.B("stag-b");var e=k.H+"//"+k.T+"?"+d.ga();v.B("stag-d");d.na(e);b.log(e,function(b){d.U(b);f.d(a,"Function")&&a.call(d)})},qa:function(){var a=document.location.hash.substring(1),b=RegExp(c.id),e=-1<document.referrer.indexOf(k.oa),f=d.j(a,"jn"),g=/^heatlink$|^select$|^pageclick$/.test(f);a&&(b.test(a)&&e&&g)&&(this.a.rnd=Math.round(Math.random()*k.w),a=
document.createElement("script"),a.setAttribute("type","text/javascript"),a.setAttribute("charset","utf-8"),a.setAttribute("src",k.protocol+"//"+c.js+f+".js?"+this.a.rnd),f=document.getElementsByTagName("script")[0],f.parentNode.insertBefore(a,f))},na:function(a){var b=e.get("Hm_unsent_"+c.id)||"",d=this.a.u?"":"&u="+encodeURIComponent(document.location.href),b=encodeURIComponent(a.replace(/^https?:\/\//,"")+d)+(b?","+b:"");e.set("Hm_unsent_"+c.id,b)},U:function(a){var b=e.get("Hm_unsent_"+c.id)||
"";b&&(a=encodeURIComponent(a.replace(/^https?:\/\//,"")),a=RegExp(a.replace(/([\*\(\)])/g,"\\$1")+"(%26u%3D[^,]*)?,?","g"),(b=b.replace(a,"").replace(/,$/,""))?e.set("Hm_unsent_"+c.id,b):e.remove("Hm_unsent_"+c.id))},gb:function(){var a=this,d=e.get("Hm_unsent_"+c.id);if(d)for(var d=d.split(","),f=function(d){b.log(k.H+"//"+decodeURIComponent(d),function(b){a.U(b)})},g=0,l=d.length;g<l;g++)f(d[g])}};return new a})();
(function(){var a=mt.event,d=mt.l;try{if(window.performance&&performance.timing&&"undefined"!==typeof h.b){var b=function(a){var b=performance.timing,d=b[a+"Start"]?b[a+"Start"]:0;a=b[a+"End"]?b[a+"End"]:0;return{start:d,end:a,value:0<a-d?a-d:0}},g=function(){var a;a=b("navigation");var f=b("request");a={netAll:f.start-a.start,netDns:b("domainLookup").value,netTcp:b("connect").value,srv:b("response").start-f.start,dom:performance.timing.domInteractive-performance.timing.fetchStart,loadEvent:b("loadEvent").end-
a.start};h.b.a.et=87;h.b.a.ep=d.stringify(a);h.b.k()};a.c(window,"load",function(){setTimeout(g,500)})}}catch(f){}})();
(function(){var a=mt.f,d=mt.lang,b=mt.event,g=mt.l;if("undefined"!==typeof h.b&&(c.med||(!a.ca||7<a.Va)&&c.cvcc)){var f,n,l,p,e=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},k=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===u)return u},v=function(a,b){var e={};e.n=f;e.t="clk";e.v=a;if(b){var k=b.getAttribute("href"),m=b.getAttribute("onclick")?""+b.getAttribute("onclick"):t,n=b.getAttribute("id")||"";l.test(k)?(e.sn="mediate",
e.snv=k):d.d(m,"String")&&l.test(m)&&(e.sn="wrap",e.snv=m);e.id=n}h.b.a.et=86;h.b.a.ep=g.stringify(e);h.b.k();for(e=+new Date;400>=+new Date-e;);};if(c.med)n="/zoosnet",f="swt",l=/swt|zixun|call|chat|zoos|business|talk|kefu|openkf|online|\/LR\/Chatpre\.aspx/i,p={click:function(){for(var a=[],b=e(document.getElementsByTagName("a")),b=[].concat.apply(b,e(document.getElementsByTagName("area"))),b=[].concat.apply(b,e(document.getElementsByTagName("img"))),d,f,g=0,k=b.length;g<k;g++)d=b[g],f=d.getAttribute("onclick"),
d=d.getAttribute("href"),(l.test(f)||l.test(d))&&a.push(b[g]);return a}};else if(c.cvcc){n="/other-comm";f="other";l=c.cvcc.q||r;var m=c.cvcc.id||r;p={click:function(){for(var a=[],b=e(document.getElementsByTagName("a")),b=[].concat.apply(b,e(document.getElementsByTagName("area"))),b=[].concat.apply(b,e(document.getElementsByTagName("img"))),d,f,g,k=0,n=b.length;k<n;k++)d=b[k],l!==r?(f=d.getAttribute("onclick"),g=d.getAttribute("href"),m?(d=d.getAttribute("id"),(l.test(f)||l.test(g)||m.test(d))&&
a.push(b[k])):(l.test(f)||l.test(g))&&a.push(b[k])):m!==r&&(d=d.getAttribute("id"),m.test(d)&&a.push(b[k]));return a}}}if("undefined"!==typeof p&&"undefined"!==typeof l){var q;n+=/\/$/.test(n)?"":"/";var x=function(a,b){if(q===b)return v(n+a,b),u;if(d.d(b,"Array")||d.d(b,"NodeList"))for(var e=0,f=b.length;e<f;e++)if(q===b[e])return v(n+a+"/"+(e+1),b[e]),u};b.c(document,"mousedown",function(a){a=a||window.event;q=a.target||a.srcElement;var b={};for(k(p,function(a,e){b[a]=d.d(e,"Function")?e():document.getElementById(e)});q&&
q!==document&&k(b,x)!==u;)q=q.parentNode})}}})();(function(){var a=mt.g,d=mt.lang,b=mt.event,g=mt.l;if("undefined"!==typeof h.b&&d.d(c.cvcf,"Array")&&0<c.cvcf.length){var f={la:function(){for(var d=c.cvcf.length,g,p=0;p<d;p++)(g=a.Z(decodeURIComponent(c.cvcf[p])))&&b.c(g,"click",f.ya())},ya:function(){return function(){h.b.a.et=86;var a={n:"form",t:"clk"};a.id=this.id;h.b.a.ep=g.stringify(a);h.b.k()}}};a.fa(function(){f.la()})}})();
(function(){var a=mt.event,d=mt.l;if(c.med&&"undefined"!==typeof h.b){var b=+new Date,g={n:"anti",sb:0,kb:0,clk:0},f=function(){h.b.a.et=86;h.b.a.ep=d.stringify(g);h.b.k()};a.c(document,"click",function(){g.clk++});a.c(document,"keyup",function(){g.kb=1});a.c(window,"scroll",function(){g.sb++});a.c(window,"unload",function(){g.t=+new Date-b;f()});a.c(window,"load",function(){setTimeout(f,5E3)})}})();})();
